name: Build
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Production CI
        run: 'npm run ci:prod'
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          coauthor_email: 'mate.homolya@gmail.com'
          coauthor_name: 'Máté Homolya'
          branch: 'master'
          directory: 'dist'

